DroneDB.Registry.Web/Startup.cs
LICENSE.md

Updated License

---

DroneDB.Registry.Web/Startup.cs

Do not enforce https

---

DroneDB.Registry.Common/DroneDB.Registry.Common.csproj
DroneDB.Registry.Common/Utils.cs
DroneDB.Registry.Web/DroneDB.Registry.Web.csproj
DroneDB.Registry.Web/Program.cs
DroneDB.Registry.sln

Check and fix config if missing or empty secret

---

DroneDB.Registry.Web/Controllers/UsersController.cs

Switch from BadRequest to Problem to return errors from API controllers

---

Registry.Web/Program.cs

Added command line help

---

Registry.Web/Properties/launchSettings.json
Registry.Web/Registry.Web.csproj
Registry.Web/Startup.cs
Registry.Web/wwwroot/index.html

Added a simple onboarding page with a link to the wiki
Fixes #2

Onboarding page

---

Registry.Web/Controllers/UsersController.cs
Registry.Web/Models/AuthenticateResponse.cs
Registry.Web/Models/ErrorResponse.cs
Registry.Web/Models/User.cs
Registry.Web/Services/UserService.cs
Registry.Web/Startup.cs

Instead of ASP.NET awkward error messages.
Also removes firstName, lastName fields (not needed at this moment).

Unified error responses

---

Registry.Common/Utils.cs

Case-sensitive FilesAreEqual

---

Registry.Adapters/ObjectSystem/PhysicalObjectSystem.cs

Fixed compiler warnings and cleanup

---

Dockerfile
Registry.Web/Controllers/UsersController.cs
Registry.Web/Models/ChangeUserPasswordRequest.cs
Registry.Web/Models/CreateUserRequest.cs
Registry.Web/Services/Adapters/UsersManager.cs
Registry.Web/Services/Ports/IUsersManager.cs
Registry.Web/Startup.cs

Config should be adjusted, it's kinda working now

Improved docker file

---

Registry.Web/Controllers/DatasetsController.cs
Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Controllers/OrganizationsController.cs
Registry.Web/Controllers/ShareController.cs
Registry.Web/Controllers/UsersController.cs

Route root changed from "ddb" to "orgs"

---

Registry.Adapters/ObjectSystem/PhysicalObjectSystem.cs
Registry.Web/Services/Adapters/ShareManager.cs

Handle empty files

---

Registry.Adapters.Test/ObjectSystem/PhysicalObjectSystemTest.cs
Registry.Adapters/ObjectSystem/PhysicalObjectSystem.cs
Registry.Web.Data/Models/Dataset.cs
Registry.Web.Data/Models/DownloadPackage.cs
Registry.Web.Data/RegistryContext.cs
Registry.Web.Test/ObjectManagerTest.cs
Registry.Web.Test/ShareManagerTest.cs
Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Models/DTO/DownloadPackageDto.cs
Registry.Web/Models/DTO/FileDescriptorDto.cs
Registry.Web/Registry.Web.csproj
Registry.Web/Services/Adapters/ChunkedUploadManager.cs
Registry.Web/Services/Adapters/DatasetsManager.cs
Registry.Web/Services/Adapters/ObjectsManager.cs
Registry.Web/Services/Adapters/OrganizationsManager.cs
Registry.Web/Services/Adapters/ShareManager.cs
Registry.Web/Services/Adapters/WebUtils.cs
Registry.Web/Services/Ports/IObjectsManager.cs
Registry.Web/Services/Ports/IUtils.cs

Adds the zip feature and Closes #76

Add zip download

---

.gitignore
Registry.Adapters.DroneDB/Ddb.cs
Registry.Web/Models/AppSettings.cs
Registry.Web/Program.cs
Registry.Web/Services/Adapters/ChunkedUploadManager.cs
Registry.Web/Services/Adapters/TokenManager.cs
Registry.Web/Services/ApplicationDbContext.cs
Registry.Web/Services/JwtInCookieMiddleware.cs
Registry.Web/Services/JwtInHeaderMiddleware.cs
Registry.Web/Services/TokenManagerMiddleware.cs
Registry.Web/Startup.cs
Registry.Web/appsettings-default.json
Registry.Web/appsettings.json

Closes #80 
Closes #75 
Closes #69

Various fixes and improvements

---

Registry.Adapters/ObjectSystem/PhysicalObjectSystem.cs
Registry.Web.Data/Models/Dataset.cs
Registry.Web.Test/DdbFactoryTest.cs
Registry.Web.Test/ObjectManagerTest.cs
Registry.Web/Controllers/DatasetsController.cs
Registry.Web/Services/Adapters/DatasetsManager.cs
Registry.Web/Services/Adapters/ObjectsManager.cs
Registry.Web/Services/Ports/IDatasetManager.cs
Registry.Web/Services/Ports/IObjectsManager.cs
Registry.Web/Utilities/Extenders.cs

Closes #82 
New endpoint as MiniReg reference implementation

Add rename endpoint

---

Registry.Web.Data/Models/Entry.cs
Registry.Web.Test/DatasetManagerTest.cs
Registry.Web.Test/ObjectManagerTest.cs
Registry.Web.Test/OrganizationManagerTest.cs
Registry.Web.Test/ShareManagerTest.cs
Registry.Web.Test/WebUtilsTest.cs
Registry.Web/Controllers/DatasetsController.cs
Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Controllers/OrganizationsController.cs
Registry.Web/Controllers/ShareController.cs
Registry.Web/Controllers/UsersController.cs
Registry.Web/Models/AppSettings.cs
Registry.Web/Models/DTO/BatchDto.cs
Registry.Web/Models/DTO/EntryDto.cs
Registry.Web/Models/DTO/ObjectDto.cs
Registry.Web/Services/Adapters/DatasetsManager.cs
Registry.Web/Services/Adapters/ObjectsManager.cs
Registry.Web/Services/Adapters/ShareManager.cs
Registry.Web/Services/Adapters/WebUtils.cs
Registry.Web/Services/Ports/IDatasetManager.cs
Registry.Web/Services/Ports/IUtils.cs
Registry.Web/Startup.cs
Registry.Web/Utilities/Extenders.cs
Registry.Web/Utilities/RoutesHelper.cs
Registry.Web/appsettings-default.json
Registry.Web/appsettings.Release.json
Registry.Web/appsettings.json

Various improvements

---

Registry.Web/Models/AppSettings.cs
Registry.Web/Models/User.cs
Registry.Web/Services/Adapters/ExternalSignInManager.cs
Registry.Web/Services/Adapters/OrganizationsManager.cs
Registry.Web/Services/Adapters/UsersManager.cs
Registry.Web/Services/ApplicationDbContext.cs
Registry.Web/Services/Ports/IOrganizationsManager.cs
Registry.Web/Services/Ports/IUsersManager.cs
Registry.Web/Startup.cs
Registry.Web/appsettings-default.json
Registry.Web/appsettings.json

Closes #61 
I was not able to test it. I followed the minireg implementation. Are the metadata populated yet?

Add remote auth provider

---

Registry.Web.Data/Models/Dataset.cs
Registry.Web.Test/ShareManagerTest.cs
Registry.Web/Services/Adapters/DatasetsManager.cs
Registry.Web/Services/Adapters/ShareManager.cs
Registry.Web/Utilities/Extenders.cs

Fix share public dataset

---

Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Services/Adapters/ObjectsManager.cs
Registry.Web/Services/Ports/IObjectsManager.cs

Added new download endpoint

---

Registry.Common/EntryType.cs

This is one of the hardest PR ever done on Registry
Ref https://github.com/DroneDB/DroneDB/issues/95

Added markdown enum value

---

Registry.Adapters/ObjectSystem/CachedS3ObjectSystem.cs

Closes #114 
Cache is now stored in a hierarchical tree structure, no more dash separator. Plus I fixed a bug in expired bucket cleanup function that was deleting the info files in certain condition. 
If this is ok we can push it to testhub

Switched to tree structure and fixed a bug in folder cleanup

---

.github/workflows/build-and-publish.yml
.github/workflows/dotnet-core.yml

Added dockerhub workflow

---

Registry.Web/Controllers/UsersController.cs
Registry.Web/Models/AuthenticateRequest.cs
Registry.Web/Models/AuthenticateResponse.cs
Registry.Web/Models/DTO/LoginResult.cs
Registry.Web/Services/Managers/ExternalSignInManager.cs
Registry.Web/Services/Managers/LocalLoginManager.cs
Registry.Web/Services/Managers/LoginManager.cs
Registry.Web/Services/Managers/RemoteLoginManager.cs
Registry.Web/Services/Managers/UsersManager.cs
Registry.Web/Services/Ports/ILoginManager.cs
Registry.Web/Services/Ports/IUsersManager.cs
Registry.Web/Startup.cs
Registry.Web/Utilities/ZipArchiveExtensions.cs

Changed zip folder separator from "\" to "/"
Closes #141

Fix linux clone

---

Registry.Web/Controllers/UsersController.cs
Registry.Web/Models/AuthenticateRequest.cs
Registry.Web/Models/AuthenticateResponse.cs
Registry.Web/Models/DTO/LoginResult.cs
Registry.Web/Services/Managers/ExternalSignInManager.cs
Registry.Web/Services/Managers/LocalLoginManager.cs
Registry.Web/Services/Managers/LoginManager.cs
Registry.Web/Services/Managers/RemoteLoginManager.cs
Registry.Web/Services/Managers/UsersManager.cs
Registry.Web/Services/Ports/ILoginManager.cs
Registry.Web/Services/Ports/IUsersManager.cs
Registry.Web/Startup.cs

In order to implement token auth I needed to do a small refactor of our auth class structure
Closes #124

Add xauth support

---

Registry.Common/CommonUtils.cs
Registry.Web.Test/PushManagerTest.cs
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Services/Managers/PushManager.cs
Registry.Web/Services/Ports/IObjectsManager.cs

Closes #139 
This PR will need a PR in DroneDB repo too. Coming soon 👍

Push now creates dataset if it does not exist

---

Registry.Web/Registry.Web.csproj
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Services/Managers/UsersManager.cs
Registry.Web/Utilities/Extenders.cs
Registry.Web/Utilities/RoutesHelper.cs

Closes #127 
It still needs testing, so this is a draft 👍

Fix organization casing and share issues

---

Registry.Adapters.DroneDB/Ddb.cs
Registry.Ports/DroneDB/IDdb.cs
Registry.Ports/DroneDB/Models/DdbAttributes.cs
Registry.Ports/DroneDB/Models/DdbMeta.cs
Registry.Web.Data/Migrations/20210510153909_SizeAndObjectsCountRemoved.Designer.cs
Registry.Web.Data/Migrations/20210510153909_SizeAndObjectsCountRemoved.cs
Registry.Web.Data/Models/Dataset.cs
Registry.Web.Test/DatasetManagerTest.cs
Registry.Web.Test/ShareManagerTest.cs
Registry.Web/Models/DTO/DatasetDto.cs
Registry.Web/Services/Adapters/WebUtils.cs
Registry.Web/Services/Managers/DatasetsManager.cs
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Services/Managers/SystemManager.cs
Registry.Web/Services/Ports/IUtils.cs
Registry.Web/Utilities/Extenders.cs

Remove update statistics

---

Registry.Adapters.DroneDB/Ddb.cs
Registry.Adapters/AdaptersUtils.cs
Registry.Adapters/ObjectSystem/CachedS3ObjectSystem.cs
Registry.Ports/DroneDB/IDdb.cs
Registry.Web.Test/ObjectManagerTest.cs
Registry.Web.Test/ShareManagerTest.cs
Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Models/DTO/FileStreamDescriptor.cs
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Services/Ports/IObjectsManager.cs

Fixes and improves the filesystem support

Improve fs support

---

Registry.Web/Startup.cs

.laz files cannot be statically served without this change.
﻿

Serve unknown file types

---

Registry.Adapters.DroneDB/Ddb.cs
Registry.Adapters.DroneDB/Registry.Adapters.DroneDB.csproj
Registry.Ports/DroneDB/IDdb.cs
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Services/Managers/PushManager.cs

Ref https://github.com/DroneDB/DroneDB/pull/264 
Performed some refactoring and whitespace / whiteline cleaning

Add IsBuildable call to know if file is buildable or not

---

Dockerfile

Fix dev certs generation

---

Registry.Adapters.DroneDB/Ddb.cs
Registry.Adapters.DroneDB/DdbMetaManager.cs
Registry.Adapters.DroneDB/Registry.Adapters.DroneDB.csproj
Registry.Ports/DroneDB/IDdb.cs
Registry.Ports/DroneDB/IDdbMetaManager.cs
Registry.Ports/DroneDB/Models/DdbMeta.cs
Registry.Ports/DroneDB/Models/DdbMetaListItem.cs
Registry.Web.Test/MetaManagerTest.cs
Registry.Web/Controllers/MetaController.cs
Registry.Web/Models/DTO/MetaDto.cs
Registry.Web/Models/DTO/MetaListItemDto.cs
Registry.Web/Services/Adapters/WebUtils.cs
Registry.Web/Services/Managers/DatasetsManager.cs
Registry.Web/Services/Managers/MetaManager.cs
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Services/Managers/PushManager.cs
Registry.Web/Services/Ports/IMetaManager.cs
Registry.Web/Startup.cs
Registry.Web/Utilities/RoutesHelper.cs

Closes https://github.com/DroneDB/Registry/issues/178
CI will fail until https://github.com/DroneDB/DDB.Bindings/pull/17 is merged and new nuget package is published.
**REST Compliant**
```
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/list
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/get​/{key}
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/add​/{key}
POST ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/set​/{key}
DELETE ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/remove​/{id}
DELETE ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/unset​/{key}
```
**NON REST Compliant** 
`key`, `path` and `data` are `formdata` parameters (`path` and `key` can also be provided via query string)
```
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/list
GET ​/orgs​/{orgSlug}​/ds​/{dsSlug}​/meta​/get​/{key}
POST …
```

Add meta endpoints

---

Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Services/Managers/CacheManager.cs

Fix thumbnail cache, display thumbnails inline

---

README.md

as per #225 , added to readme the line that fixes the docker build. I also added a few notes to ease initial use of the local registry.

update readme with build fix and notes

---

Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Services/Ports/IObjectsManager.cs

Ad title says 🚀 
Added `/list` and `/search` optional `type` parameter (`EntryType`) to filter a specific entry type.
It is needed to integrate WebODM and DroneDB when listing folders https://github.com/OpenDroneMap/WebODM/issues/939

Added optional type filter in list and search

---

Dockerfile

Added libnexus to docker image run stage

---

Registry.Web/Controllers/ObjectsController.cs

Enables range requests processing for build files.

Enable range requests processing

---

README.md
docker/production/docker-compose.yml
docker/testing/docker-compose.yml

Addresses https://github.com/DroneDB/Registry/issues/246 thanks to [borsti67](https://github.com/borsti67)

Fix README and improve docker-compose

---

Registry.Web/Controllers/DatasetsController.cs
Registry.Web/Models/DTO/DatasetDto.cs
Registry.Web/Services/Managers/DatasetsManager.cs
Registry.Web/Services/Managers/PushManager.cs
Registry.Web/Services/Managers/ShareManager.cs
Registry.Web/Services/Ports/IDatasetManager.cs
Registry.Web/Startup.cs

This PR is support for https://github.com/DroneDB/Hub/pull/70

API changes to fix edge cases

---

Registry.Web/Controllers/ShareController.cs
Registry.Web/Models/DTO/ShareInitDto.cs
Registry.Web/Models/DTO/TagDto.cs
Registry.Web/Properties/launchSettings.json
Registry.Web/Services/Managers/ShareManager.cs

Fix init/share, update hub

---

Registry.Web.Test/ShareManagerTest.cs
Registry.Web/Services/Managers/AuthManager.cs
Registry.Web/Services/Managers/DatasetsManager.cs
Registry.Web/Services/Ports/IAuthManager.cs

As title says, partially addresses https://github.com/DroneDB/Registry/issues/259

Only the owner can add datasets in public organizations

---

docker/production/docker-compose.yml
docker/testing/docker-compose.yml

Added tmpfs mount to docker compose files

---

Registry.Adapters/DroneDB/DDBWrapper.cs
Registry.Adapters/DroneDB/Ddb.cs

Fixed list logic

---

.github/workflows/release.yml
Registry.Common/CommonExtenders.cs
Registry.Web/Properties/PublishProfiles/linux-arm64.pubxml
Registry.Web/Registry.Web.csproj
Registry.Web/Registry.Web.csproj.DotSettings
Registry.Web/Services/Managers/UsersManager.cs

- Added new linux arm64 build
- Fixed `admin` field serialization in JWT token
- Fixed user metadata synchronization

Added new build and various fixes

---

Registry.Web/Services/Managers/AuthManager.cs

Fixed user check

---

Registry.Adapters.Ddb.Test/Registry.Adapters.Ddb.Test.csproj
Registry.Adapters.Test/Registry.Adapters.Test.csproj
Registry.Adapters/DroneDB/DbSyncManager.cs
Registry.Adapters/DroneDB/Ddb.cs
Registry.Adapters/DroneDB/NativeDdbWrapper.cs
Registry.Adapters/Registry.Adapters.csproj
Registry.Adapters/Thumbnail/LocalThumbnailGenerator.cs
Registry.Adapters/Thumbnail/RemoteThumbnailGenerator.cs
Registry.Common/Registry.Common.csproj
Registry.Ports/Registry.Ports.csproj
Registry.Test.Common/Registry.Test.Common.csproj
Registry.Web.Data.MySqlMigrations/Registry.Web.Data.MySqlMigrations.csproj
Registry.Web.Data.SqliteMigrations/Registry.Web.Data.SqliteMigrations.csproj
Registry.Web.Data/Registry.Web.Data.csproj
Registry.Web.Identity.MySqlMigrations/Registry.Web.Identity.MySqlMigrations.csproj
Registry.Web.Identity.SqliteMigrations/Registry.Web.Identity.SqliteMigrations.csproj
Registry.Web.Identity/Registry.Web.Identity.csproj
Registry.Web.Test/ObjectManagerTest.cs
Registry.Web.Test/Registry.Web.Test.csproj
Registry.Web.Test/ShareManagerTest.cs
Registry.Web/Controllers/ObjectsController.cs
Registry.Web/Registry.Web.csproj
Registry.Web/Services/Managers/ObjectsManager.cs
Registry.Web/Startup.cs
Registry.Web/Utilities/Extenders.cs

- Fixed bug in thumbnail generation
- Improved checks and logging
- Updated nuget packages

Thumbnail generation improvements
